### ISSUE TITLE
NodeJS v0.10 npm install errors CentOS 7

### ISSUE THREAD

**Issue by zhmeniapep** [quartzjer/ursa#112]
Hello, see log please.

# npm install ursa
npm WARN package.json dclogger@0.0.3 No repository field.
npm WARN package.json dcutils@0.0.20 No repository field.
\
> ursa@0.9.0 install /home/ppm/nodejs_api/node_modules/ursa
> node-gyp rebuild

make: Entering directory `/home/ppm/nodejs_api/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc: In static member function ‘static void RsaWrap::InitClass(v8::Handle<v8::Object>)’:
../src/ursaNative.cc:354:17: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Reset’
     constructor.Reset(target->GetIsolate(), tpl->GetFunction());
                 ^
../src/ursaNative.cc:354:31: error: ‘class v8::Object’ has no member named ‘GetIsolate’
     constructor.Reset(target->GetIsolate(), tpl->GetFunction());
                               ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::GetExponent(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:45:64: error: no matching function for call to ‘Nan::ReturnValue<v8::Value>::Set(v8::Handle<v8::Value>)’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:545:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->e));
     ^
../src/ursaNative.cc:45:64: note: candidates are:
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:545:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->e));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note: template<class S> void Nan::ReturnValue<T>::Set(const v8::Local<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const v8::Local<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const v8::Local<T>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:545:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->e));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note: template<class S> void Nan::ReturnValue<T>::Set(const Nan::Global<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const Global<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const Nan::Global<S>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:545:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->e));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note: void Nan::ReturnValue<T>::Set(bool) [with T = v8::Value]
   inline void Set(bool value) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘bool’
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note: void Nan::ReturnValue<T>::Set(double) [with T = v8::Value]
   inline void Set(double i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘double’
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note: void Nan::ReturnValue<T>::Set(int32_t) [with T = v8::Value; int32_t = int]
   inline void Set(int32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘int32_t {aka int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note: void Nan::ReturnValue<T>::Set(uint32_t) [with T = v8::Value; uint32_t = unsigned int]
   inline void Set(uint32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘uint32_t {aka unsigned int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note: template<class S> void Nan::ReturnValue<T>::Set(S*) [with S = S; T = v8::Value]
   inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   mismatched types ‘S*’ and ‘v8::Handle<v8::Value>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:545:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->e));
     ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::GetPrivateExponent(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:45:64: error: no matching function for call to ‘Nan::ReturnValue<v8::Value>::Set(v8::Handle<v8::Value>)’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:561:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->d));
     ^
../src/ursaNative.cc:45:64: note: candidates are:
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:561:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->d));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note: template<class S> void Nan::ReturnValue<T>::Set(const v8::Local<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const v8::Local<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const v8::Local<T>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:561:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->d));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note: template<class S> void Nan::ReturnValue<T>::Set(const Nan::Global<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const Global<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const Nan::Global<S>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:561:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->d));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note: void Nan::ReturnValue<T>::Set(bool) [with T = v8::Value]
   inline void Set(bool value) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘bool’
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note: void Nan::ReturnValue<T>::Set(double) [with T = v8::Value]
   inline void Set(double i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘double’
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note: void Nan::ReturnValue<T>::Set(int32_t) [with T = v8::Value; int32_t = int]
   inline void Set(int32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘int32_t {aka int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note: void Nan::ReturnValue<T>::Set(uint32_t) [with T = v8::Value; uint32_t = unsigned int]
   inline void Set(uint32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘uint32_t {aka unsigned int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note: template<class S> void Nan::ReturnValue<T>::Set(S*) [with S = S; T = v8::Value]
   inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   mismatched types ‘S*’ and ‘v8::Handle<v8::Value>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:561:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->d));
     ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::GetModulus(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:45:64: error: no matching function for call to ‘Nan::ReturnValue<v8::Value>::Set(v8::Handle<v8::Value>)’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:576:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->n));
     ^
../src/ursaNative.cc:45:64: note: candidates are:
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:576:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->n));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note: template<class S> void Nan::ReturnValue<T>::Set(const v8::Local<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const v8::Local<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const v8::Local<T>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:576:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->n));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note: template<class S> void Nan::ReturnValue<T>::Set(const Nan::Global<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const Global<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const Nan::Global<S>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:576:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->n));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note: void Nan::ReturnValue<T>::Set(bool) [with T = v8::Value]
   inline void Set(bool value) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘bool’
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note: void Nan::ReturnValue<T>::Set(double) [with T = v8::Value]
   inline void Set(double i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘double’
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note: void Nan::ReturnValue<T>::Set(int32_t) [with T = v8::Value; int32_t = int]
   inline void Set(int32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘int32_t {aka int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note: void Nan::ReturnValue<T>::Set(uint32_t) [with T = v8::Value; uint32_t = unsigned int]
   inline void Set(uint32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘uint32_t {aka unsigned int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note: template<class S> void Nan::ReturnValue<T>::Set(S*) [with S = S; T = v8::Value]
   inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   mismatched types ‘S*’ and ‘v8::Handle<v8::Value>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:576:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bignumToBuffer(obj->rsa->n));
     ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::GetPrivateKeyPem(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:45:64: error: no matching function for call to ‘Nan::ReturnValue<v8::Value>::Set(v8::Handle<v8::Value>)’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:628:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
../src/ursaNative.cc:45:64: note: candidates are:
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:628:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note: template<class S> void Nan::ReturnValue<T>::Set(const v8::Local<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const v8::Local<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const v8::Local<T>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:628:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note: template<class S> void Nan::ReturnValue<T>::Set(const Nan::Global<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const Global<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const Nan::Global<S>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:628:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note: void Nan::ReturnValue<T>::Set(bool) [with T = v8::Value]
   inline void Set(bool value) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘bool’
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note: void Nan::ReturnValue<T>::Set(double) [with T = v8::Value]
   inline void Set(double i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘double’
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note: void Nan::ReturnValue<T>::Set(int32_t) [with T = v8::Value; int32_t = int]
   inline void Set(int32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘int32_t {aka int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note: void Nan::ReturnValue<T>::Set(uint32_t) [with T = v8::Value; uint32_t = unsigned int]
   inline void Set(uint32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘uint32_t {aka unsigned int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note: template<class S> void Nan::ReturnValue<T>::Set(S*) [with S = S; T = v8::Value]
   inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   mismatched types ‘S*’ and ‘v8::Handle<v8::Value>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:628:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::GetPublicKeyPem(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:45:64: error: no matching function for call to ‘Nan::ReturnValue<v8::Value>::Set(v8::Handle<v8::Value>)’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:655:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
../src/ursaNative.cc:45:64: note: candidates are:
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:655:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note: template<class S> void Nan::ReturnValue<T>::Set(const v8::Local<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const v8::Local<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:33:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const v8::Local<T>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:655:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note: template<class S> void Nan::ReturnValue<T>::Set(const Nan::Global<S>&) [with S = S; T = v8::Value]
   template <typename S> inline void Set(const Global<S> &handle) {
                                     ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:39:37: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   ‘v8::Handle<v8::Value>’ is not derived from ‘const Nan::Global<S>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:655:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
In file included from ../node_modules/nan/nan_callbacks.h:85:0,
                 from ../node_modules/nan/nan.h:150,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note: void Nan::ReturnValue<T>::Set(bool) [with T = v8::Value]
   inline void Set(bool value) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:47:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘bool’
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note: void Nan::ReturnValue<T>::Set(double) [with T = v8::Value]
   inline void Set(double i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:53:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘double’
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note: void Nan::ReturnValue<T>::Set(int32_t) [with T = v8::Value; int32_t = int]
   inline void Set(int32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:59:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘int32_t {aka int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note: void Nan::ReturnValue<T>::Set(uint32_t) [with T = v8::Value; uint32_t = unsigned int]
   inline void Set(uint32_t i) {
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:65:15: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘uint32_t {aka unsigned int}’
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note: template<class S> void Nan::ReturnValue<T>::Set(S*) [with S = S; T = v8::Value]
   inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
               ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:15: note:   template argument deduction/substitution failed:
../src/ursaNative.cc:45:64: note:   mismatched types ‘S*’ and ‘v8::Handle<v8::Value>’
 #define NanReturnValue(value) { info.GetReturnValue().Set(value); return; }
                                                                ^
../src/ursaNative.cc:655:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(bioToBuffer(bio));
     ^
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
make: Leaving directory `/home/ppm/nodejs_api/node_modules/ursa/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-229.14.1.el7.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ppm/nodejs_api/node_modules/ursa
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! ursa@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.0 install script.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Thank in advance,
Best regards

**Comment by adrai** [comment]
can you try with latest master?
npm i quartzjer/ursa

**Comment by quartzjer** [comment]
v0.9.1 is out now too and should build again for node v0.10

**Comment by zhmeniapep** [comment]
Thank you very much, URSA has been installed.
