### ISSUE TITLE
Error while trying to install ursa with npm

### ISSUE THREAD

**Issue by saadeljaouhari** [quartzjer/ursa#123]
I have this error when i try to install ursa (RSA public/private key OpenSSL bindings for node and io.js)

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-39-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/saad/Bureau/kevinIdP/node_modules/ursa
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0

Do i have to add some dependencies ? Thanks for the interest

**Comment by gerdschoen** [comment]
Hello saadeljaouhari, 
I had this error on debian 8 too. After installing nodejs as described in: 

https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager?utm_source=%5Bdeliciuos%5D&utm_medium=twitter#debian-and-ubuntu-based-linux-distributions

it seems to work.
Hth, Gerd

**Comment by saadeljaouhari** [comment]
thank you gerdschoen for the answer it realy helped me.
