### ISSUE TITLE
ursa version 0.9.1 needs at least Node 0.10 but only requires engine >= 0.8

### ISSUE THREAD

**Issue by ctarrington** [quartzjer/ursa#128]
If I fully specify the minor version in my package.json I am able to depend on ursa@0.8.5 for node 0.8 and depend on ursa@0.9.1 for node 0.10 and up. 

However, I can't figure out a way to write a package.json that includes ursa and works well under old and new versions of node. When I do an npm install with "ursa": ">=0.8.5" or "~0.8.5 || ~0.9.1" it always attempts to install ursa 0.9.1 which fails for node 0.8 and works on node 0.10 and up.

[Gory details from Travis](https://travis-ci.org/HelloWallet/node-soap/jobs/111138865)

Would it be possible to change the engine section from "node": ">=0.6.0" to "node": ">=0.10"? 
If so, I am optimistic that "ursa": "0.8.5 || >=0.9.2" will do the trick.

Many thanks for maintaining ursa!

**Comment by quartzjer** [comment]
I don't see why not, tis more of a everyone-maintain repo too, pull requests welcomed for this or others :)

**Comment by ctarrington** [comment]
Thanks - I'll make a pull request
