### ISSUE TITLE
Can't install ursa@0.9.3

### ISSUE THREAD

**Issue by doronMendelson** [quartzjer/ursa#133]
Hi,

I have node version 4.4.2 and npm version 3.8.6 on Centos 5.6

I'm getting the following error:

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-573.7.1.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ppc/ppcReport/node_modules/ursa
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
ppc@1.0.0 /home/ppc/ppcReport
├─┬ async@2.0.0-rc.3
│ └── lodash@4.11.0
├── chai@3.5.0  extraneous
└─┬ istanbul@0.3.22
  ├── async@1.5.2
  └─┬ handlebars@4.0.5
    └── async@1.5.2

npm WARN ppc@1.0.0 No repository field.
npm ERR! Linux 2.6.32-573.7.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! ursa@0.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ursa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ppc/ppcReport/npm-debug.log

Please help

**Comment by sleepyfox** [comment]
I get the same error as a dependency of another project (soap depends on ursa)

**Comment by roshanpaiva** [comment]
+1

**Comment by anonimoaveces** [comment]
Hi, any found a solution?

I'm suffering same problem.

**Comment by herom** [comment]
We have also reports of failing installs on Windows machines (seems like `node-gyp` is making troubles) for our library (`node-soap`) since we use your package as a dependency :cry: 

Is there anything we can do to help fixing this issue?

**Comment by quartzjer** [comment]
v0.9.4 is out, give it a try and re-open or file new issue if there's still problems, sorry that took a while!  I'd love to find a new maintainer for this project if anyone is willing to take it over :)
