### ISSUE TITLE
Node v6 "v8::ObjectTemplate::Set() with non-primitive values is deprecated"

### ISSUE THREAD

**Issue by mwain** [quartzjer/ursa#135]
Testing this on Node v6 and throwing warnings
`v8::ObjectTemplate::Set() with non-primitive values is deprecated`

See nodejs/node#6216 and nodejs/node#6228

**Comment by TylerGarlick** [comment]
+1

**Comment by tieblumer** [comment]
+1

**Comment by superherointj** [comment]
+1

**Comment by diekson** [comment]
+1

**Comment by mwain** [comment]
See PR #137
