### ISSUE TITLE
npm install ursa   on a fresh debian jessie 8.5

### ISSUE THREAD

**Issue by 6illes** [quartzjer/ursa#143]
http://pastebin.com/gUZd0LAU

gilles@c2m:~/dev/bot.web2$ npm install

> ursa@0.9.4 install /mnt/data/dev/bot.web2/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/mnt/data/dev/bot.web2/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
make: g++: Command not found
ursaNative.target.mk:96: recipe for target 'Release/obj.target/ursaNative/src/ursaNative.o' failed
make: **\* [Release/obj.target/ursaNative/src/ursaNative.o] Error 127
make: Leaving directory '/mnt/data/dev/bot.web2/node_modules/ursa/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.5.1-std-1
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/data/dev/bot.web2/node_modules/ursa
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN install:ursa@0.9.4 ursa@0.9.4 install: `node-gyp rebuild`
npm WARN install:ursa@0.9.4 Exit status 1
smtp.bot@1.0.0 /mnt/data/dev/bot.web2

npm updated npm and node-gyp

Q? Do we have to install build-essential and g++ to have ursa installed ?

**Comment by get-trucked** [comment]
Looks like you need c/c++ compiler, make and python as this is a dependency of node-gyp. ran into a similar problem when building it into a docker container.

Screen shot taken from node-gyp repo.
![image](https://cloud.githubusercontent.com/assets/14492694/17679280/e34e9824-638e-11e6-882a-9111d6444bc3.png)

**Comment by 6po** [comment]
thanks

**Comment by 6illes** [comment]
was more of an open question actually
