### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by prasadh13** [quartzjer/ursa#177]
I have ursa v0.9.4 in my package.json.
The npm install failed with this error - 

`npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ursa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.`

Node: v6.11.3
npm: v3.10.10
OS: MacOS Mojave

Please help. TIA

**Comment by rzr** [comment]
Node 6 is a bit outdated , try v8 until v10 is supported

**Comment by prasadh13** [comment]
Got it. Thanks!
