### ISSUE TITLE
ursa how to solve it? warning C4005 warning C4506

### ISSUE THREAD

**Issue by Tinario** [quartzjer/ursa#33]
C:\Windows\system32>npm install ursa
npm http GET https://registry.npmjs.org/ursa
npm http 304 https://registry.npmjs.org/ursa

> ursa@0.8.0 install C:\Windows\system32\node_modules\ursa
> node-gyp configure build && node install.js

C:\Windows\system32\node_modules\ursa>node "C:\Program Files\nodejs\node_modules
\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure bu
ild
  asprintf.cc
  ursaNative.cc
c:\windows\system32\node_modules\ursa\src\ursaNative.h(6): warning C4005: 'BUIL
DING_NODE_EXTENSION' : macro redefinition [C:\Windows\system32\node_modules\urs
a\build\ursaNative.vcxproj]
          command-line arguments :  see previous definition of 'BUILDING_NODE_E
  XTENSION'
C:\Users\Tinario.node-gyp\0.10.15\deps\v8\include\v8.h(184): warning C4506: no
 definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::H
andle<T>)' [C:\Windows\system32\node_modules\ursa\build\ursaNative.vcxproj]
          with
          [
              T=v8::Object
          ]
     Creating library C:\Windows\system32\node_modules\ursa\build\Release\ursaN
  ative.lib and object C:\Windows\system32\node_modules\ursa\build\Release\ursa
  Native.exp
  Generating code
  Finished generating code
  ursaNative.vcxproj -> C:\Windows\system32\node_modules\ursa\build\Release\ur
  saNative.node
ursa@0.8.0 node_modules\ursa
## done that steps below for first, but when install ursa show that warning messages in yellow text above.

WINDOWS 7 32BIT
VISUAL C++ 2010
C:\OpenSSL-Win32
npm install -g node-gyp

**Comment by brst-dev** [comment]
was this ever actually solved?
