### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by SLaks** [quartzjer/ursa#8]
The legacy generateKey() implementation is missing a return.  
Shouldn't https://github.com/Obvious/ursa/blob/master/src/ursaNative.cc#L287 be `return`ed?

Visual C++ says

> ..\src\ursaNative.cc(205): warning C4244: 'argument' : conversion from 'ssize_t' to 'int', possible loss of data  
> ..\src\ursaNative.cc(224): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data 

GCC says

> In file included from ../src/ursaNative.cc:3:0:
> ../src/ursaNative.h:6:0: warning: "BUILDING_NODE_EXTENSION" redefined [enabled by default]
> 
> ../src/ursaNative.cc: In function ‘bool getArgInt(const v8::Arguments&, int, int_)’:
> ../src/ursaNative.cc:293:76: warning: ignoring return value of ‘int asprintf(char__, const char_, ...)’, declared with attribute warn_unused_result [-Wunused-result]
> 
> ../src/ursaNative.cc: In function ‘bool hasArgument(const v8::Arguments&, int)’:
> ../src/ursaNative.cc:152:51: warning: ignoring return value of ‘int asprintf(char*_, const char_, ...)’, declared with attribute warn_unused_result [-Wunused-result]
> 
> ../src/ursaNative.cc: In function ‘bool isBuffer(const v8::Arguments&, int)’:
> ../src/ursaNative.cc:167:68: warning: ignoring return value of ‘int asprintf(char*_, const char_, ...)’, declared with attribute warn_unused_result [-Wunused-result]
> 
> ../src/ursaNative.cc: In function ‘bool isString(const v8::Arguments&, int)’:
> ../src/ursaNative.cc:185:68: warning: ignoring return value of ‘int asprintf(char*_, const char_, ...)’, declared with attribute warn_unused_result [-Wunused-result]

**Comment by xr0master** [comment]
Hey. I have there warnings too.
Windows 10
Visual Studio 2015
```
..\src\ursaNative.cc(165): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [Z:\NodeJS projects\anycuby-server\node_modules\ursa\build\ursaNati
ve.vcxproj]
..\src\ursaNative.cc(180): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [Z:\NodeJS projects\anycuby-server\node_modules\ursa\build\ursaNati
ve.vcxproj]
..\src\ursaNative.cc(387): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [Z:\NodeJS projects\anycuby-server\node_modules\ursa\build\ursaN
ative.vcxproj]
..\src\ursaNative.cc(388): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [Z:\NodeJS projects\anycuby-server\node_modules\ursa\build\ursaN
ative.vcxproj]
..\src\ursaNative.cc(695): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [Z:\NodeJS projects\anycuby-server\node_modules\ursa\build\ursaNativ
e.vcxproj]
..\src\ursaNative.cc(743): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [Z:\NodeJS projects\anycuby-server\node_modules\ursa\build\ursaNativ
e.vcxproj]
..\src\ursaNative.cc(788): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [Z:\NodeJS projects\anycuby-server\node_modules\ursa\build\ursaNativ
e.vcxproj]
..\src\ursaNative.cc(835): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [Z:\NodeJS projects\anycuby-server\node_modules\ursa\build\ursaNativ
e.vcxproj]
```
