### ISSUE TITLE
Make update(...) functions to return self

### ISSUE THREAD

**Issue by pfumagalli** [quartzjer/ursa#86]
It would be über nice if `signer.update(...)` and `verifier.update(...)` were to return `self` so that methods could be easily chained like:

```javascript
var signature = ursa.createSigner('SHA256')
                    .update('foo')
                    .update('bar')
                    .sign(...);
```

Should I submit a PR?

**Comment by quartzjer** [comment]
Yeah, that would be great :)

**Comment by pfumagalli** [comment]
Pull request in #87
